### ISSUE TITLE
Footpath parallel to road not showing up

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/osm2streets#107]
This footway is not imported by osm2streets it seems: https://www.openstreetmap.org/way/1087921367#map=18/53.81506/-1.53894

Important one because the only way to go North up Scott Hall Road from Buslingthorpe Lane without mixing with fast moving traffic. Split out from #80.

**Comment by Robinlovelace** [comment]
For anyone who wants to reproduce this: https://a-b-street.github.io/osm2streets/#16/53.8187/-1.5399

**Comment by dabreegster** [comment]
So actually, this does show up, but you have to opt into the "use mapped footways" experiment. Because this separate footway is tagged as a sidewalk, we exclude it normally, because in general importing these without further snapping to the main road causes havoc. It's the goal of this repo to eventually solve that problem in a robust way and enable that setting by default.
![Screenshot from 2022-11-07 20-17-11](https://user-images.githubusercontent.com/1664407/200406833-14892a21-b3d7-4a5a-91e9-5493234e8d26.png)

**Comment by dabreegster** [comment]
And for an example of why opting into these `footway=sidewalk` cases is not so straightforward, here's two different types of problems seen at https://a-b-street.github.io/osm2streets/#18/47.64968/-122.33368:
![Screenshot from 2022-11-07 20-20-55](https://user-images.githubusercontent.com/1664407/200407351-e0bd4cb0-64be-4965-bad4-c8919431fa08.png)
The mapped sidewalks cut off (and are very tedious to map + maintain in OSM, though there was a QGIS plugin at SoTM that could help), complicate the intersection geometry substantially, and can't be edited in cross-section view in context of the full road

**Comment by Robinlovelace** [comment]
Great stuff, wasn't sure it was actually a bug, should have tested! Better to map it in OSM as a sidewalk on the road geometry or as a standalone feature? Marginal and pros and cons both ways...

**Comment by Robinlovelace** [comment]
Just had a look at aerial imagery basemap and yeah, seems tricky to map. This is one where some of the underlying data could be fixed with an editor that allowed you to visually drag and drop lanes and set widths to ensure the space is filled. Is there a missing verge in the empty space between the carriageway and the pavements there?
