### ISSUE TITLE
`GenerateIntersectionGeometry` makes existing intersections larger

### ISSUE THREAD

**Issue by matthieu-foucault** [a-b-street/osm2streets#143]
Not sure if this is a known issue and/or belongs in #136 .

Using the lane editor, intersections get wider every time they are recalculated, quickly going from this:
![image](https://user-images.githubusercontent.com/2684022/206042176-0d17df54-c3c9-4a34-b532-9d62dba17deb.png)

to this:

![image](https://user-images.githubusercontent.com/2684022/206042309-920c05ae-6c44-4d4d-8db2-73be5f6e135c.png)

If this is not something that's being worked on already, I'm happy to take a crack at it, with a bit of guidance.

**Comment by dabreegster** [comment]
https://github.com/a-b-street/osm2streets/commit/27676ea1b34e7c2203bfc008785993466d39d448#diff-97e56e5c0796be8f5261b7c46c7a821a12cdc86a58023bb1081087e586d29942
It's due to this. I'm working on #136 actively right now and it's kind of a big mess. I'm hoping the dust will settle in a few days. Are you interested in diving into the scary but satisfying world of trimming road centers and making intersection polygons?

**Comment by matthieu-foucault** [comment]
For sure! Right now I'm looking at indicating the forwards direction of the road, as you mentioned in https://github.com/a-b-street/osm2streets/issues/132#issuecomment-1339162927, I'm hoping to have a PR for that early tomorrow
