### ISSUE TITLE
Bindings for Java

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#68]
Let's start the equivalent of [osm2street-js](https://github.com/a-b-street/osm2streets/tree/main/osm2streets-js), but for Java. At an extremely cursory glance, https://github.com/jni-rs/jni-rs looks popular, but there are likely many options out there

**Comment by dabreegster** [comment]
https://blog.frankel.ch/start-rust/7/ and https://docs.rs/jni/latest/jni/ look straightforward to me. I'll try exposing the same `osm2streets-js` API like this. Not sure how packaging / publishing works, but not important yet

**Comment by dabreegster** [comment]
Actually, https://github.com/dushistov/flapigen-rs might be a higher-level approach

**Comment by BudgieInWA** [comment]
I am able to build and run the build native library locally! My next challenge is to using it as a library in the JOSM2Streets plugin. I have the JOSM plugin building using gradle, but I only just have a grasp of how that build system is working, and don't know how distributing the built plugin will work yet. Including the native library will be tricky, but I think I there is a satisfying solution:

It looks like we can package the native libraries in a `.jar` while building `osm2streets-java`, and modify the JNI class to load the appropriate library out of the JAR, according to a couple of the answers at https://stackoverflow.com/questions/2937406/how-to-bundle-a-native-library-and-a-jni-library-inside-a-jar. Maybe this library will be good: https://github.com/scijava/native-lib-loader?

Then I can copy the `.jar` into the JOSM plugin project and add it as a dependency in the standard way (which I hope is easy). Publishing the bundled JAR to Maven should also be "straight forward".

**Comment by dabreegster** [comment]
`native-lib-loader` indeed looks great. Do callers need to depend both on it and our jar with all the native builds, or can we have a single library that depends on this loader and calls it? I'm still a bit confused how this all wires together; I wonder if there's a real example of a project out there with everything set up.

Another question is how to build for all the platforms sanely. We can do this with Github actions, but I've never attempted to automatically bundle resulting files from each platform into one final asset.

**Comment by BudgieInWA** [comment]
My understanding is that the result is a completely self contained `.jar`, with all of the JNI stuff as an implementation detail.

The idea is that `System.loadLibrary(libName)` loads the native lib by finding it in the system paths, but `System.load(absolutePath)` loads a lib from a specific absolute path. A `.jar` is actually just a `.zip` file, so resources can be packaged in alongside the Java bytecode. The solution for "statically linked" JNI dependencies, is to package the native libs in the `.jar`, then at runtime, extract the appropriate lib into a temp dir and `System.load()` it (with a fallback to `System.loadLibrary()` if the current system's lib isn't packaged, so people can compile their own). [This answer to that SO question](https://stackoverflow.com/a/49500154) has an implementation. I believe `native-lib-loader` provides that logic.

Packaging a `.jar` with resources is a pretty standard thing for java build systems to do I think. If I get to it first, I'll look into doing it with Gradle, because that's what I've got working with JOSM2Streets.

**Comment by BudgieInWA** [comment]
Packaging the `.jar` is as easy as `jar cf StreetNetwork.jar StreetNetwork.class -C ../target/debug/ libosm2streets_java.so`. I'm gonna stick with bash scripts for building, gradle is not going to make our lives easier at this stage. I'm working on a proof-of-concept version of generating the `.jar` and using it in the JOSM plugin.

**Comment by dabreegster** [comment]
Next steps: improve API exposed in the bindings, and publish (with multiple platform support)
