### ISSUE TITLE
Bug: incorrect order of bus:lanes when the driving side is left

### ISSUE THREAD

**Issue by k-yle** [a-b-street/osm2streets#83]
If the driving side is set to "left", the values in `bus:lanes` are unexpectedly flipped. 

Example: [Go here](https://a-b-street.github.io/osm2streets/#20.5/-36.85183/174.76605), change the driving mode to left. Note how the bus lane is on the very right, when it should be on the very left.

the value of `bus:lanes=designated|yes|yes` should not be flipped in left-hand mode

![image](https://user-images.githubusercontent.com/16009897/188015291-6b10cc02-c723-4488-89c9-a011d32b0992.png)

---

[Another example, without dual carriageway](https://a-b-street.github.io/osm2streets/#20.5/-36.79778/174.76255): The bus lane should be on the southern side, not in the middle

```
bus:lanes:backward=designated|yes
lanes=3
lanes:backward=2
lanes:forward=1
```

![image](https://user-images.githubusercontent.com/16009897/188015432-b8ecd354-90cb-4ab4-bfa1-30bc223d390c.png)

**Comment by dabreegster** [comment]
Thanks for reporting! Currently the OSM way tags -> lane parsing code is around here: https://github.com/a-b-street/osm2streets/blob/3fd448555a9153cfb417fe92df68d741e76055a6/street_network/src/lane_specs.rs#L160
The problem is that `fwd_side` and `back_side` are ordered from innermost (close to the center of the road) to outer (close to the kerb). But `bus:lanes` handling and similar things are index based.

This `lane_specs.rs` file is a total mess, and we have a rewrite started at https://github.com/a-b-street/osm2lanes. Unfortunately that library immediately breaks due to the deprecated `sidewalk=none` tag (which is another issue about how strict that library is), so I can't easily see if this sort of index-based case works well with left-handed driving yet or not.

I'll try to make a decision soon about whether to keep improving the existing lane parsing code or cutover to osm2lanes and focus investments there.
